---
title: "St. Louis Lead Inequity"
format: html 
execute: 
  echo: true
  warning: false
---

```{r}
library(tidyverse)
library(janitor)
```

```{r}
stl_lead <- read_csv(here::here("data","stl_lead.csv")) %>% 
  clean_names()
```

## New data frame

```{r}
stl_lead_prop <- dplyr::mutate(stl_lead,prop_white = white/total_pop *100)
```

## Create a scattter plot

```{r}
stl_lead_plot <- ggplot(data = stl_lead_prop, aes(x = pct_elevated, y = prop_white)) + geom_point(aes(size = prop_white, color = prop_white), alpha = .6) + labs(title = "Children elevated blood lead levels vs White Identifying", x = "Elevated Blood Lead levels (%)", y = "White Identifying (%)")

stl_lead_plot

```

Elevated blood lead levels increase as the number of children that identify as white decreases

```{r}
ggsave(here::here("figs","scatterplot_pcte_white.png"), height = 6, width = 5)
```

## Histogram

```{r}
histogram_stl_lead <- ggplot(data = stl_lead_prop, aes(x=pct_elevated)) + geom_histogram(fill = 'yellow',color = 'purple')

histogram_stl_lead

ggsave(here::here("figs","histogram_stl_lead.jpg"))
```
